

 POST http://localhost:3001/Transferencia
 Content-Type: application/json

 {
     "idconta": 5,
     "idcontadestino": 7,
     "valor": 100,
     "email": "pedroutumi@gmail.com",
     "datatransf": "2006-11-20",
     "comentario": "AEEEEEEEEEEEEEEEEEEEEE",
     "chavedestino": "13731593912"
 }

